### ISSUE TITLE
Unicode file name

### ISSUE THREAD

**Issue by caiguanhao** [benbalter/word-to-markdown-server#31]
### Describe the bug

Webpage shows "Internal Server Error".

word-to-markdown-server's console shows "Encoding::CompatibilityError - incompatible character encodings: ASCII-8BIT and UTF-8"

### Steps to reproduce the behavior

1. Upload a docx file whose name includes unicode characters (for example `你好.docx`)

### Expected behavior

No error occurred.

### Resolutions

1. Remove unicode characters in file name then upload.

2. Or, add `.force_encoding('UTF-8')` in `server.rb`

```ruby
      render_template :display, md: md, html: html, filename: params['doc'][:filename].force_encoding('UTF-8').sub(/\.docx?$/, '')
```

**Comment by benbalter** [comment]
@caiguanhao Thanks for this. Would you be interested in submitted a pull request to resolve this issue?
