### ISSUE TITLE
Current version requires linux container on docker windows desktop

### ISSUE THREAD

**Issue by peterennisrda** [benbalter/word-to-markdown-server#9]
Docker Windows Desktop
Windows 10 1809

If windows container is selected this error occurs:

![Capture192](https://user-images.githubusercontent.com/1280523/57114098-7dd23f80-6cfc-11e9-9e55-5e1daec27632.png)

The readme should be clear about this.

**Comment by benbalter** [comment]
@peterennisrda would you be willing to submit a pull request to update the documentation?

**Comment by peterennisrda** [comment]
Yes 👍
